
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import { Poppins } from "next/font/google";
import Navbar from "@/components/Navbar";
import AuthProciders from "@/components/providers/AuthProviders";
import { Toaster } from "@/components/ui/sonner"

const poppins = Poppins({ subsets: ['latin'], weight: '400' })

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${poppins.className} antialiased`}
      >
      <AuthProciders>
       <SidebarProvider>
         <AppSidebar />
           <main className="w-full h-full flex flex-col">
          <Navbar />
           {children}
           </main>
           <Toaster/>
         </SidebarProvider>
         </AuthProciders>
      </body>
    </html>
  );
}
